//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _100autotjek.Localize {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("100autotjek.Localize.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afbestille.
        /// </summary>
        public static string Alert_Cancel {
            get {
                return ResourceManager.GetString("Alert_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kan ikke genkende CPR-nummer. Prøv venligst igen eller indtast det manuelt..
        /// </summary>
        public static string Alert_CPRNumberErrorMessage {
            get {
                return ResourceManager.GetString("Alert_CPRNumberErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPR nummer fejl.
        /// </summary>
        public static string Alert_CPRNumberErrorTitle {
            get {
                return ResourceManager.GetString("Alert_CPRNumberErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver info er ikke gyldig. Prøv igen..
        /// </summary>
        public static string Alert_DriverInfoInvalidErrorMessage {
            get {
                return ResourceManager.GetString("Alert_DriverInfoInvalidErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver info fejl.
        /// </summary>
        public static string Alert_DriverInfoInvalidErrorTitle {
            get {
                return ResourceManager.GetString("Alert_DriverInfoInvalidErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunne ikke indlæse driver oplysninger. Prøv igen..
        /// </summary>
        public static string Alert_DriverInfoLoadErrorMessage {
            get {
                return ResourceManager.GetString("Alert_DriverInfoLoadErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forbindelsen mislykkedes.
        /// </summary>
        public static string Alert_DriverInfoLoadErrorTitle {
            get {
                return ResourceManager.GetString("Alert_DriverInfoLoadErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivér adgang.
        /// </summary>
        public static string Alert_EnableCameraAccess {
            get {
                return ResourceManager.GetString("Alert_EnableCameraAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tjek din internet forbindelse og prøv igen..
        /// </summary>
        public static string Alert_InternetConnectionErrorMessage {
            get {
                return ResourceManager.GetString("Alert_InternetConnectionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingen internetforbindelse.
        /// </summary>
        public static string Alert_InternetConnectionErrorTitle {
            get {
                return ResourceManager.GetString("Alert_InternetConnectionErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intet kamera til rådighed.
        /// </summary>
        public static string Alert_NoCameraErrorMessage {
            get {
                return ResourceManager.GetString("Alert_NoCameraErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kamera fejl.
        /// </summary>
        public static string Alert_NoCameraErrorTitle {
            get {
                return ResourceManager.GetString("Alert_NoCameraErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunne ikke indlæse nummerplader. Prøv igen..
        /// </summary>
        public static string Alert_NumberPlatesLoadErrorMessage {
            get {
                return ResourceManager.GetString("Alert_NumberPlatesLoadErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forbindelsen mislykkedes.
        /// </summary>
        public static string Alert_NumberPlatesLoadErrorTitle {
            get {
                return ResourceManager.GetString("Alert_NumberPlatesLoadErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kameraet er utilgængeligt.
        /// </summary>
        public static string Alert_PermissionErrorMessage {
            get {
                return ResourceManager.GetString("Alert_PermissionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tilladelser nægtet.
        /// </summary>
        public static string Alert_PermissionErrorTitle {
            get {
                return ResourceManager.GetString("Alert_PermissionErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indlæser....
        /// </summary>
        public static string BusyIndicatorTitle {
            get {
                return ResourceManager.GetString("BusyIndicatorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tilbage.
        /// </summary>
        public static string CarInfoBack {
            get {
                return ResourceManager.GetString("CarInfoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Næste synsdato.
        /// </summary>
        public static string CarInfoCheckDate {
            get {
                return ResourceManager.GetString("CarInfoCheckDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Udstyr.
        /// </summary>
        public static string CarInfoEquipment {
            get {
                return ResourceManager.GetString("CarInfoEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pris.
        /// </summary>
        public static string CarInfoPrice {
            get {
                return ResourceManager.GetString("CarInfoPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Første registrering dato.
        /// </summary>
        public static string CarInfoRegistrationDate {
            get {
                return ResourceManager.GetString("CarInfoRegistrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilometertal.
        /// </summary>
        public static string CarInfoRun {
            get {
                return ResourceManager.GetString("CarInfoRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BIL DETALJER.
        /// </summary>
        public static string CarInfoTitle {
            get {
                return ResourceManager.GetString("CarInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REDIGERE.
        /// </summary>
        public static string CarsForSaleEdit {
            get {
                return ResourceManager.GetString("CarsForSaleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GEM.
        /// </summary>
        public static string CarsForSaleSave {
            get {
                return ResourceManager.GetString("CarsForSaleSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string ContinueButton {
            get {
                return ResourceManager.GetString("ContinueButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KØRESEDDEL.
        /// </summary>
        public static string DriverInfoTitle {
            get {
                return ResourceManager.GetString("DriverInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BIL DETALJER.
        /// </summary>
        public static string EditCarInfoTitle {
            get {
                return ResourceManager.GetString("EditCarInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SLET.
        /// </summary>
        public static string ListOfCarsRemove {
            get {
                return ResourceManager.GetString("ListOfCarsRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Søg.
        /// </summary>
        public static string ListOfCarsSearch {
            get {
                return ResourceManager.GetString("ListOfCarsSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BILER TIL SALG.
        /// </summary>
        public static string ListOfCarsTitle {
            get {
                return ResourceManager.GetString("ListOfCarsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BILER TIL SALG.
        /// </summary>
        public static string MainMenuCarsForSale {
            get {
                return ResourceManager.GetString("MainMenuCarsForSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KØRESEDDEL.
        /// </summary>
        public static string MainMenuDoc {
            get {
                return ResourceManager.GetString("MainMenuDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRØVEPLADER.
        /// </summary>
        public static string MainMenuNumberPlate {
            get {
                return ResourceManager.GetString("MainMenuNumberPlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPFØLGNING.
        /// </summary>
        public static string MainMenuPhone {
            get {
                return ResourceManager.GetString("MainMenuPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPSLAG.
        /// </summary>
        public static string MainMenuSearch {
            get {
                return ResourceManager.GetString("MainMenuSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BILLEDE MED LOGO.
        /// </summary>
        public static string MainMenuSticker {
            get {
                return ResourceManager.GetString("MainMenuSticker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error with sending email to dealer! Please try again..
        /// </summary>
        public static string ResultErrorMessage {
            get {
                return ResourceManager.GetString("ResultErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document has been successfully generated and sent at your email..
        /// </summary>
        public static string ResultSuccessMessage {
            get {
                return ResourceManager.GetString("ResultSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESULTAT.
        /// </summary>
        public static string ResultTitle {
            get {
                return ResourceManager.GetString("ResultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eller indtast CPR.
        /// </summary>
        public static string ScanDrivingCPRNumber {
            get {
                return ResourceManager.GetString("ScanDrivingCPRNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placer kørekortet så CPR-nr. (4d) er i rammen.
        /// </summary>
        public static string ScanDrivingInstructionOfScan {
            get {
                return ResourceManager.GetString("ScanDrivingInstructionOfScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPR NUMMER.
        /// </summary>
        public static string ScanDrivingTitle {
            get {
                return ResourceManager.GetString("ScanDrivingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sidst registrerede nr.plade.
        /// </summary>
        public static string SearchCarByPlate {
            get {
                return ResourceManager.GetString("SearchCarByPlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eller VIN-rn..
        /// </summary>
        public static string SearchCarByVIN {
            get {
                return ResourceManager.GetString("SearchCarByVIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Søg.
        /// </summary>
        public static string SearchCarSearch {
            get {
                return ResourceManager.GetString("SearchCarSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPSLAG HOS SKAT.
        /// </summary>
        public static string SearchCarTitle {
            get {
                return ResourceManager.GetString("SearchCarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tegn over linjen.
        /// </summary>
        public static string SignatureCaption {
            get {
                return ResourceManager.GetString("SignatureCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SLET.
        /// </summary>
        public static string SignatureClear {
            get {
                return ResourceManager.GetString("SignatureClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du har valgt følgende bil:.
        /// </summary>
        public static string SignatureSelectedCar {
            get {
                return ResourceManager.GetString("SignatureSelectedCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bedes du underskrive dit navn:.
        /// </summary>
        public static string SignatureText {
            get {
                return ResourceManager.GetString("SignatureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNDERSKRIFT.
        /// </summary>
        public static string SignatureTitle {
            get {
                return ResourceManager.GetString("SignatureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunde.
        /// </summary>
        public static string TestDriveInfoDriver {
            get {
                return ResourceManager.GetString("TestDriveInfoDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string TestDriveInfoEmail {
            get {
                return ResourceManager.GetString("TestDriveInfoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slut.
        /// </summary>
        public static string TestDriveInfoEndTime {
            get {
                return ResourceManager.GetString("TestDriveInfoEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string TestDriveInfoPhone {
            get {
                return ResourceManager.GetString("TestDriveInfoPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vælg.
        /// </summary>
        public static string TestDriveInfoPickerTitle {
            get {
                return ResourceManager.GetString("TestDriveInfoPickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prøveplader.
        /// </summary>
        public static string TestDriveInfoPlateNumber {
            get {
                return ResourceManager.GetString("TestDriveInfoPlateNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string TestDriveInfoStartTime {
            get {
                return ResourceManager.GetString("TestDriveInfoStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prøveperiode.
        /// </summary>
        public static string TestDriveInfoTime {
            get {
                return ResourceManager.GetString("TestDriveInfoTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KØRESEDDEL.
        /// </summary>
        public static string TestDriveInfoTitle {
            get {
                return ResourceManager.GetString("TestDriveInfoTitle", resourceCulture);
            }
        }
    }
}
